name: Build and Test GreenPulse

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Check project files
        run: |
          echo "Проверка структуры проекта GreenPulse"
          ls -la
          test -f README.md
          test -f feature.txt
          test -f app.py

      - name: Run Python script
        run: python app.py

      - name: Run tests imitation
        run: echo "Тесты проекта GreenPulse успешно выполнены"
